name = "Air"
uuid = "0c3b9dc7-9fea-4423-80ce-ed7c11218d4a"
authors = ["Noah C. Benson"]
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataStructures = "0.18"
Random = "1.10"
SparseArrays = "1.10"
julia = "1.10"
